---
title: "Validation of OSU HTTF PG-28 Test Using RELAP5-3D"
author: "Joshua Halsted"
date: "1/29/2022"
output: 
  pdf_document:
  keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load_Experimental_Data}
#PG_28_Data_Quality <-read.csv("C:/Users/17577/Thesis_Work/RELAP_FILES/PG_28_Files/PG28_Data_Quality.csv")
#PG_28_Data_Trend <-read.csv("C:/Users/17577/Thesis_Work/RELAP_FILES/PG_28_Files/PG28_Data_Trend.csv")
```

# Test Description

# Experimental Results




```{r Load_File_List, eval=FALSE, include=FALSE}
myData = read.delim("C:/Users/17577/Thesis_Work/RELAP_FILES/Automation_Tools/CSV_Files.txt", header = FALSE)
test_data = read.csv(myData$V1[1])
for(i in 1:nrow(myData)) {
  print(myData$V1[i])
  
}
```


## Introduction


```{r cars}
math = 2 + 2
```

## Materials and Methods


## Discussion

### Results


```{r Iteration_4}
reticulate::source_python("C:/Users/17577/Thesis_Work/RELAP_FILES/Automation_Tools/Strip2CSV.py")
read.csv("C:/Users/17577/Thesis_Work/RELAP_FILES/PG_28_Files/Iteration_4/Workbooks/Output_Flow_Rate_Point_4.csv")
```


### Conclusions

## References

\clearpage

## Appendix




